{
	"schema_version": "1.6.0",
	"id": "CVE-2023-38898",
	"modified": "2025-01-16T09:12:12.179905Z",
	"published": "2023-08-15T17:15:12Z",
	"aliases": [
		"BIT-python-2022-48566",
		"BIT-python-2023-38898",
		"BIT-python-min-2022-48566",
		"CVE-2022-48566",
		"GHSA-cgfh-jp5w-8cmx",
		"GHSA-crhm-wc96-7579",
		"PSF-2023-5",
		"PSF-2023-6",
		"PSF-2023-7"
	],
	"details": "An issue in Python cpython v.3.7 allows an attacker to obtain sensitive information via the _asyncio._swap_current_task component. NOTE: this is disputed by the vendor because (1) neither 3.7 nor any other release is affected (it is a bug in some 3.12 pre-releases); (2) there are no common scenarios in which an adversary can call _asyncio._swap_current_task but does not already have the ability to call arbitrary functions; and (3) there are no common scenarios in which sensitive information, which is not already accessible to an adversary, becomes accessible through this bug.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "python3.12",
				"purl": "pkg:deb/debian/python3.12?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.12.0~b4-1"
						}
					]
				}
			],
			"versions": [
				"3.12.0~a5-1",
				"3.12.0~a7-1",
				"3.12.0~b1-1",
				"3.12.0~b2-1",
				"3.12.0~b2-2",
				"3.12.0~b2-3",
				"3.12.0~b3-1"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-38898.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://github.com/python/cpython/issues/105987"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2023-38898"
		}
	]
}
