{
	"schema_version": "1.6.0",
	"id": "CVE-2019-12761",
	"modified": "2024-06-30T12:01:22Z",
	"published": "2019-06-06T19:29:00Z",
	"aliases": [
		"GHSA-r6v3-hpxj-r8rv",
		"PYSEC-2019-199",
		"SNYK-PYTHON-PYXDG-174562"
	],
	"related": [
		"DLA-1819-1",
		"DLA-2727-1",
		"USN-4700-1"
	],
	"details": "A code injection issue was discovered in PyXDG before 0.26 via crafted Python code in a Category element of a Menu XML document in a .menu file. XDG_CONFIG_DIRS must be set up to trigger xdg.Menu.parse parsing within the directory containing this file. This is due to a lack of sanitization in xdg/Menu.py before an eval call.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.0/AV:N/AC:H/PR:N/UI:R/S:U/C:H/I:H/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "pyxdg",
				"purl": "pkg:deb/debian/pyxdg?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0.26-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "low"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-12761.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:12",
				"name": "pyxdg",
				"purl": "pkg:deb/debian/pyxdg?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0.26-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "low"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-12761.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "pyxdg",
				"purl": "pkg:deb/debian/pyxdg?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "0.26-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "low"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2019-12761.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://snyk.io/vuln/SNYK-PYTHON-PYXDG-174562"
		},
		{
			"type": "WEB",
			"url": "https://gist.github.com/dhondta/b45cd41f4186110a354dc7272916feba"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2019/06/msg00006.html"
		},
		{
			"type": "WEB",
			"url": "https://lists.debian.org/debian-lts-announce/2021/08/msg00003.html"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2019-12761"
		}
	]
}
