{
	"schema_version": "1.6.0",
	"id": "CVE-2009-3695",
	"modified": "2024-06-30T12:01:22Z",
	"published": "2009-10-13T10:30:00Z",
	"aliases": [
		"GHSA-p6m5-h7pp-v2x5",
		"PYSEC-2009-4"
	],
	"related": [
		"DSA-1905-1"
	],
	"details": "Algorithmic complexity vulnerability in the forms library in Django 1.0 before 1.0.4 and 1.1 before 1.1.1 allows remote attackers to cause a denial of service (CPU consumption) via a crafted (1) EmailField (email address) or (2) URLField (URL) that triggers a large amount of backtracking in a regular expression.",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "python-django",
				"purl": "pkg:deb/debian/python-django?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.1.1-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "medium"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2009-3695.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:12",
				"name": "python-django",
				"purl": "pkg:deb/debian/python-django?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.1.1-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "medium"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2009-3695.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "python-django",
				"purl": "pkg:deb/debian/python-django?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.1.1-1"
						}
					]
				}
			],
			"ecosystem_specific": {
				"urgency": "medium"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2009-3695.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "http://secunia.com/advisories/36948"
		},
		{
			"type": "ADVISORY",
			"url": "http://secunia.com/advisories/36968"
		},
		{
			"type": "ADVISORY",
			"url": "http://www.debian.org/security/2009/dsa-1905"
		},
		{
			"type": "FIX",
			"url": "http://www.djangoproject.com/weblog/2009/oct/09/security/"
		},
		{
			"type": "FIX",
			"url": "http://www.vupen.com/english/advisories/2009/2871"
		},
		{
			"type": "FIX",
			"url": "http://www.securityfocus.com/bid/36655"
		},
		{
			"type": "WEB",
			"url": "http://bugs.debian.org/cgi-bin/bugreport.cgi?bug=550457"
		},
		{
			"type": "WEB",
			"url": "http://groups.google.com/group/django-users/browse_thread/thread/15df9e45118dfc51/"
		},
		{
			"type": "WEB",
			"url": "http://www.openwall.com/lists/oss-security/2009/10/13/6"
		},
		{
			"type": "WEB",
			"url": "https://exchange.xforce.ibmcloud.com/vulnerabilities/53727"
		}
	]
}
