{
	"schema_version": "1.6.0",
	"id": "CVE-2023-6110",
	"modified": "2025-01-14T11:55:56.896389Z",
	"published": "2024-11-17T11:15:06Z",
	"aliases": [
		"GHSA-2ppf-2m6f-6v6f"
	],
	"related": [
		"RHSA-2024:2737",
		"RHSA-2024:2769",
		"UBUNTU-CVE-2023-6110",
		"USN-6668-1"
	],
	"details": "A flaw was found in OpenStack. When a user tries to delete a non-existing access rule in it's scope, it deletes other existing access rules which are not associated with any application credentials.",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "python-openstackclient",
				"purl": "pkg:deb/debian/python-openstackclient?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"5.4.0-4",
				"5.5.0-1",
				"5.5.0-2",
				"5.6.0-1",
				"5.6.0-2",
				"5.7.0-1",
				"5.8.0-1",
				"5.8.0-2",
				"6.0.0-1",
				"6.0.0-2",
				"6.0.0-3",
				"6.0.0-4",
				"6.1.0-1",
				"6.2.0-1",
				"6.2.0-2",
				"6.2.0-3",
				"6.2.0-4",
				"6.3.0-1",
				"6.3.0-2",
				"6.3.0-3",
				"6.5.0-1",
				"6.5.0-2",
				"6.6.0-1",
				"6.6.0-2",
				"6.6.0-3",
				"6.6.0-4",
				"6.6.0-5",
				"7.0.0-1",
				"7.1.0-1",
				"7.1.1-1",
				"7.1.1-2"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-6110.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:12",
				"name": "python-openstackclient",
				"purl": "pkg:deb/debian/python-openstackclient?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"6.0.0-4",
				"6.1.0-1",
				"6.2.0-1",
				"6.2.0-2",
				"6.2.0-3",
				"6.2.0-4",
				"6.3.0-1",
				"6.3.0-2",
				"6.3.0-3",
				"6.5.0-1",
				"6.5.0-2",
				"6.6.0-1",
				"6.6.0-2",
				"6.6.0-3",
				"6.6.0-4",
				"6.6.0-5",
				"7.0.0-1",
				"7.1.0-1",
				"7.1.1-1",
				"7.1.1-2"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-6110.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "python-openstackclient",
				"purl": "pkg:deb/debian/python-openstackclient?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "6.3.0-2"
						}
					]
				}
			],
			"versions": [
				"6.0.0-4",
				"6.1.0-1",
				"6.2.0-1",
				"6.2.0-2",
				"6.2.0-3",
				"6.2.0-4",
				"6.3.0-1"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2023-6110.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:2737"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:2769"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2212960"
		},
		{
			"type": "WEB",
			"url": "https://access.redhat.com/security/cve/CVE-2023-6110"
		},
		{
			"type": "WEB",
			"url": "https://code.engineering.redhat.com/gerrit/gitweb?p=python-openstackclient.git;a=commit;h=7a7c364bdd7b2cd2b56e73724110710a68d58abf"
		},
		{
			"type": "WEB",
			"url": "https://review.opendev.org/c/openstack/python-openstackclient/+/888697"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2023-6110"
		}
	]
}
