{
	"schema_version": "1.6.0",
	"id": "CVE-2024-2199",
	"modified": "2024-09-18T03:24:53.180768Z",
	"published": "2024-05-28T12:15:08Z",
	"related": [
		"ALSA-2024:3837",
		"ALSA-2024:4235",
		"RLSA-2024:3837",
		"RLSA-2024:4235",
		"SUSE-SU-2024:2910-1",
		"SUSE-SU-2024:3082-1",
		"SUSE-SU-2024:3218-1",
		"SUSE-SU-2024:3257-1",
		"openSUSE-SU-2024:14227-1"
	],
	"details": "A denial of service vulnerability was found in 389-ds-base ldap server. This issue may allow an authenticated user to cause a server crash while modifying `userPassword` using malformed input.",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "389-ds-base",
				"purl": "pkg:deb/debian/389-ds-base?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"1.4.4.11-2",
				"1.4.4.16-1",
				"1.4.4.17-1",
				"2.0.11-1",
				"2.0.11-2",
				"2.0.14-1",
				"2.0.15-1",
				"2.0.15-1.1",
				"2.3.1+dfsg1-1",
				"2.3.1-1",
				"2.3.4+dfsg1-1",
				"2.3.4+dfsg1-1.1",
				"2.4.4+dfsg1-1",
				"2.4.4+dfsg1-3",
				"2.4.5+dfsg1-1",
				"3.0.2+dfsg1-1",
				"3.1.1+dfsg1-1"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2024-2199.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:12",
				"name": "389-ds-base",
				"purl": "pkg:deb/debian/389-ds-base?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"2.3.1+dfsg1-1",
				"2.3.4+dfsg1-1",
				"2.3.4+dfsg1-1.1",
				"2.4.4+dfsg1-1",
				"2.4.4+dfsg1-3",
				"2.4.5+dfsg1-1",
				"3.0.2+dfsg1-1",
				"3.1.1+dfsg1-1"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2024-2199.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:13",
				"name": "389-ds-base",
				"purl": "pkg:deb/debian/389-ds-base?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.1.1+dfsg1-1"
						}
					]
				}
			],
			"versions": [
				"2.3.1+dfsg1-1",
				"2.3.4+dfsg1-1",
				"2.3.4+dfsg1-1.1",
				"2.4.4+dfsg1-1",
				"2.4.4+dfsg1-3",
				"2.4.5+dfsg1-1",
				"3.0.2+dfsg1-1"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2024-2199.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:3591"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:3837"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:4092"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:4209"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:4210"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:4235"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:4633"
		},
		{
			"type": "ADVISORY",
			"url": "https://access.redhat.com/errata/RHSA-2024:5690"
		},
		{
			"type": "REPORT",
			"url": "https://bugzilla.redhat.com/show_bug.cgi?id=2267976"
		},
		{
			"type": "WEB",
			"url": "https://access.redhat.com/security/cve/CVE-2024-2199"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2024-2199"
		}
	]
}
