{
	"schema_version": "1.6.0",
	"id": "DLA-2540-1",
	"modified": "2023-06-28T06:25:16.594537Z",
	"published": "2021-02-01T00:00:00Z",
	"related": [
		"CVE-2021-3281"
	],
	"summary": "python-django - security update",
	"details": "\nIt was discovered that there was a potential directory-traversal in\n[Django](https://www.djangoproject.com/), a popular Python-based web\ndevelopment framework.\n\n\n* [CVE-2021-3281](https://security-tracker.debian.org/tracker/CVE-2021-3281)\n\n\nFor Debian 9 Stretch, these problems have been fixed in version\n1:1.10.7-2+deb9u10.\n\n\nWe recommend that you upgrade your python-django packages.\n\n\nFurther information about Debian LTS security advisories, how to apply\nthese updates to your system and frequently asked questions can be\nfound at: <https://wiki.debian.org/LTS>\n\n\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:9",
				"name": "python-django",
				"purl": "pkg:deb/debian/python-django?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.10.7-2+deb9u10"
						}
					]
				}
			],
			"versions": [
				"1:1.10.7-2",
				"1:1.10.7-2+deb9u1",
				"1:1.10.7-2+deb9u2",
				"1:1.10.7-2+deb9u3",
				"1:1.10.7-2+deb9u4",
				"1:1.10.7-2+deb9u5",
				"1:1.10.7-2+deb9u6",
				"1:1.10.7-2+deb9u7",
				"1:1.10.7-2+deb9u8",
				"1:1.10.7-2+deb9u9"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dla-osv/DLA-2540-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.debian.org/lts/security/2021/dla-2540"
		}
	]
}
