{
	"schema_version": "1.6.0",
	"id": "DSA-4598-1",
	"modified": "2024-01-09T20:28:54.422062Z",
	"published": "2020-01-07T00:00:00Z",
	"related": [
		"CVE-2019-19844"
	],
	"summary": "python-django - security update",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:9",
				"name": "python-django",
				"purl": "pkg:deb/debian/python-django?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.10.7-2+deb9u7"
						}
					]
				}
			],
			"versions": [
				"1:1.10.7-2",
				"1:1.10.7-2+deb9u1",
				"1:1.10.7-2+deb9u2",
				"1:1.10.7-2+deb9u3",
				"1:1.10.7-2+deb9u4",
				"1:1.10.7-2+deb9u5",
				"1:1.10.7-2+deb9u6"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dsa-osv/DSA-4598-1.json"
			}
		},
		{
			"package": {
				"ecosystem": "Debian:10",
				"name": "python-django",
				"purl": "pkg:deb/debian/python-django?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.11.27-1~deb10u1"
						}
					]
				}
			],
			"versions": [
				"1:1.11.21-1",
				"1:1.11.22-1",
				"1:1.11.22-1~deb10u1",
				"1:1.11.23-1~deb10u1"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dsa-osv/DSA-4598-1.json"
			}
		}
	]
}
