{
	"schema_version": "1.6.0",
	"id": "DSA-3115-1",
	"modified": "2023-10-16T00:06:13.095845Z",
	"published": "2014-12-29T00:00:00Z",
	"related": [
		"CVE-2014-9130"
	],
	"summary": "pyyaml - security update",
	"details": "\nJonathan Gray and Stanislaw Pitucha found an assertion failure in the \nway wrapped strings are parsed in Python-YAML, a YAML parser and emitter \nfor Python. An attacker able to load specially crafted YAML input into an\napplication using python-yaml could cause the application to crash.\n\n\nFor the stable distribution (wheezy), this problem has been fixed in\nversion 3.10-4+deb7u1.\n\n\nFor the upcoming stable distribution (jessie), this problem has been\nfixed in version 3.11-2.\n\n\nFor the unstable distribution (sid), this problem has been fixed in\nversion 3.11-2.\n\n\nWe recommend that you upgrade your pyyaml packages.\n\n\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:7",
				"name": "pyyaml",
				"purl": "pkg:deb/debian/pyyaml?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "3.10-4+deb7u1"
						}
					]
				}
			],
			"versions": [
				"3.10-4"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dsa-osv/DSA-3115-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.debian.org/security/2014/dsa-3115"
		}
	]
}
