{
	"schema_version": "1.6.0",
	"id": "DSA-2444-1",
	"modified": "2023-10-16T00:11:15.058826Z",
	"published": "2012-03-29T00:00:00Z",
	"related": [
		"CVE-2012-0215"
	],
	"summary": "tryton-server - privilege escalation",
	"details": "\nIt was discovered that the Tryton application framework for Python\nallows authenticated users to escalate their privileges by editing the\nMany2Many field.\n\n\nFor the stable distribution (squeeze), this problem has been fixed in\nversion 1.6.1-2+squeeze1.\n\n\nFor the unstable distribution (sid), this problem has been fixed in\nversion 2.2.2-1.\n\n\nWe recommend that you upgrade your tryton-server packages.\n\n\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:6.0",
				"name": "tryton-server",
				"purl": "pkg:deb/debian/tryton-server?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1.6.1-2+squeeze1"
						}
					]
				}
			],
			"versions": [
				"1.6.1-2"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dsa-osv/DSA-2444-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.debian.org/security/2012/dsa-2444"
		}
	]
}
