{
	"schema_version": "1.6.0",
	"id": "CVE-2022-25304",
	"modified": "2024-09-18T03:12:19.606221Z",
	"published": "2022-08-23T05:15:07Z",
	"aliases": [
		"GHSA-mfpj-3qhm-976m"
	],
	"details": "All versions of package opcua; all versions of package asyncua are vulnerable to Denial of Service (DoS) due to a missing limitation on the number of received chunks - per single session or in total for all concurrent sessions. An attacker can exploit this vulnerability by sending an unlimited number of huge chunks (e.g. 2GB each) without sending the Final closing chunk.",
	"severity": [
		{
			"type": "CVSS_V3",
			"score": "CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H"
		}
	],
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:11",
				"name": "python-opcua",
				"purl": "pkg:deb/debian/python-opcua?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						}
					]
				}
			],
			"versions": [
				"0.98.11-1",
				"0.98.11-2"
			],
			"ecosystem_specific": {
				"urgency": "not yet assigned"
			},
			"database_specific": {
				"source": "https://storage.googleapis.com/cve-osv-conversion/osv-output/CVE-2022-25304.json"
			}
		}
	],
	"references": [
		{
			"type": "REPORT",
			"url": "https://github.com/FreeOpcUa/python-opcua/issues/1466"
		},
		{
			"type": "WEB",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-2988731"
		},
		{
			"type": "WEB",
			"url": "https://security.snyk.io/vuln/SNYK-PYTHON-OPCUA-2988730"
		},
		{
			"type": "ADVISORY",
			"url": "https://security-tracker.debian.org/tracker/CVE-2022-25304"
		}
	]
}
