{
	"schema_version": "1.6.0",
	"id": "DSA-2705-1",
	"modified": "2023-10-16T00:11:27.275202Z",
	"published": "2013-06-10T00:00:00Z",
	"related": [
		"CVE-2013-2132"
	],
	"summary": "pymongo - denial of service",
	"details": "\nJibbers McGee discovered that PyMongo, a high-performance schema-free\ndocument-oriented data store, is prone to a denial-of-service\nvulnerability.\n\n\nAn attacker can remotely trigger a NULL pointer dereference causing MongoDB\nto crash.\n\n\nThe oldstable distribution (squeeze) is not affected by this issue.\n\n\nFor the stable distribution (wheezy), this problem has been fixed in\nversion 2.2-4+deb7u1.\n\n\nFor the testing distribution (jessie), this problem has been fixed in\nversion 2.5.2-1.\n\n\nFor the unstable distribution (sid), this problem has been fixed in\nversion 2.5.2-1.\n\n\nWe recommend that you upgrade your pymongo packages.\n\n\n",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:7",
				"name": "pymongo",
				"purl": "pkg:deb/debian/pymongo?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "2.2-4+deb7u1"
						}
					]
				}
			],
			"versions": [
				"2.2-4"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dsa-osv/DSA-2705-1.json"
			}
		}
	],
	"references": [
		{
			"type": "ADVISORY",
			"url": "https://www.debian.org/security/2013/dsa-2705"
		}
	]
}
