{
	"schema_version": "1.6.0",
	"id": "DLA-3164-1",
	"modified": "2024-01-09T20:33:20.905490Z",
	"published": "2022-10-27T00:00:00Z",
	"related": [
		"CVE-2020-24583",
		"CVE-2020-24584",
		"CVE-2021-23336",
		"CVE-2021-3281",
		"CVE-2022-34265"
	],
	"summary": "python-django - security update",
	"affected": [
		{
			"package": {
				"ecosystem": "Debian:10",
				"name": "python-django",
				"purl": "pkg:deb/debian/python-django?arch=source"
			},
			"ranges": [
				{
					"type": "ECOSYSTEM",
					"events": [
						{
							"introduced": "0"
						},
						{
							"fixed": "1:1.11.29-1+deb10u2"
						}
					]
				}
			],
			"versions": [
				"1:1.11.21-1",
				"1:1.11.22-1",
				"1:1.11.22-1~deb10u1",
				"1:1.11.23-1~deb10u1",
				"1:1.11.27-1~deb10u1",
				"1:1.11.28-1~deb10u1",
				"1:1.11.29-1~deb10u1"
			],
			"database_specific": {
				"source": "https://storage.googleapis.com/debian-osv/dla-osv/DLA-3164-1.json"
			}
		}
	]
}
